language: python
python:
    - "2.7"
before_install:
    - deactivate
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy python-nose python-vtk
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
install: python setup.py build_ext --inplace
script: make test
