language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
  
before_install:
    - deactivate
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy python-nose python-vtk
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
    - "pip install codecov"
    - "pip install -r requirements.txt --use-mirrors"
install: python setup.py build_ext --inplace
script: 
  - nosetests -v --with-coverage
  #coverage run --source=tract_querier setup.py test
after_success: 
  - codecov

